name: finance_project
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  device_preview: ^1.1.0
  fl_chart: ^0.36.0
  font_awesome_flutter: ^9.1.0 #https://pub.dev/packages/font_awesome_flutter
  flutter_colorpicker: ^0.6.0 #https://pub.dev/packages/flutter_colorpicker
  provider: ^6.0.1 #https://pub.dev/packages/provider

dev_dependencies:
  flutter_test:
    sdk: flutter
  #flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
